FROM playstation/spark

# poetry
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    POETRY_VERSION=1.2.0 \
    POETRY_HOME="/opt/poetry" \
    POETRY_NO_INTERACTION=1

ENV PATH=$POETRY_HOME/bin:$PATH

RUN curl -sSL curl -sSL https://install.python-poetry.org | python3
RUN chmod 777 $POETRY_HOME/bin/poetry

COPY pyproject.toml .

# Project initialization
RUN poetry config virtualenvs.create false \
    && poetry install
